service: serverless-aws

provider:
  name: aws
  runtime: nodejs12.x
  profile: devProfile
  stage: dev

plugins:
  - serverless-offline

functions:
  api:
    handler: src/api/api.handler
    events:
      - http:
          path: /api
          method: GET
          cors: true
  todos:
    handler: src/api/todos.handler
    events:
      - http:
          path: /todos/{id}
          method: GET
          request:
            parameters:
              id: true
  todo:
    handler: src/api/todo.handler
    events:
      - http:
          path: /todo
          method: GET
